# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
        - master
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: '0'

      - name: Generate Git Tag
        id: generate_tag
        run: |
          const  VERSION_PREFIX = "v"
          const  VERSION_MAJOR_MINOR = "1.0"
          const VERSION_PATCH = $(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
          if [ -z "$VERSION_PATCH" ]; then
           VERSION_PATCH = 0
          else
           VERSION_PATCH = $((VERSION_PATCH + 1))
          fi
          NEW_TAG="STAGING - ${VERSION_PREFIX} ${VERSION_MAJOR_MINOR}"
          echo "Generated new tag: $NEW_TAG"

      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

