name: Tag on Push to Master with Specific Merge Message

on:
  push:
    branches:
      - master

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get last commit message
        id: last_commit
        run: echo "MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Check if commit message contains 'web'
        id: check_message
        run: |
          if  "${{ env.MESSAGE }}" == *"new action"* ; then
            echo "contains_web=true" >> $GITHUB_ENV
          else
            echo "contains_web=false" >> $GITHUB_ENV
        shell: bash

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        if: env.contains_web == 'true'

      - name: Create new tag
        id: tag
        run: |
          TAG_NAME="v${{ steps.date.outputs.DATE }}"
          git tag $TAG_NAME
          echo "::set-output name=TAG::$TAG_NAME"
        if: env.contains_web == 'true'

      - name: Push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin ${{ steps.tag.outputs.TAG }}
        if: env.contains_web == 'true'
