name: Deploy Action

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
        - master
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
#
#      - name: Generate Git Tag
#        id: generate_tag
#        run: |
#          VERSION_PREFIX="V"
#          VERSION_MAJOR_MINOR="1.0"
#          VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
#           if [ -z "$VERSION_PATCH" ]; then
#             VERSION_PATCH = 0
#           else
#             VERSION_PATCH = $((VERSION_PATCH + 1))
#           fi
#          NEW_TAG="STAGING - ${VERSION_PREFIX} ${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
#          echo "Generated new tag: $NEW_TAG" >> $GITHUB_ENV
#
      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag "STAGING"
          git push origin STAGING
          echo "Generated new tag: STAGING" >> $GITHUB_ENV
